# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from ecommerce.v1 import product_pb2 as ecommerce_dot_v1_dot_product__pb2

GRPC_GENERATED_VERSION = '1.84.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in ecommerce/v1/product_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ProductCatalogServiceStub:
    """ProductCatalogService stores products and prices them.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AddProduct = channel.unary_unary(
                '/ecommerce.v1.ProductCatalogService/AddProduct',
                request_serializer=ecommerce_dot_v1_dot_product__pb2.AddProductRequest.SerializeToString,
                response_deserializer=ecommerce_dot_v1_dot_product__pb2.AddProductResponse.FromString,
                _registered_method=True)
        self.GetProduct = channel.unary_unary(
                '/ecommerce.v1.ProductCatalogService/GetProduct',
                request_serializer=ecommerce_dot_v1_dot_product__pb2.GetProductRequest.SerializeToString,
                response_deserializer=ecommerce_dot_v1_dot_product__pb2.GetProductResponse.FromString,
                _registered_method=True)
        self.SearchProducts = channel.unary_stream(
                '/ecommerce.v1.ProductCatalogService/SearchProducts',
                request_serializer=ecommerce_dot_v1_dot_product__pb2.SearchProductsRequest.SerializeToString,
                response_deserializer=ecommerce_dot_v1_dot_product__pb2.SearchProductsResponse.FromString,
                _registered_method=True)
        self.BulkAddProducts = channel.stream_unary(
                '/ecommerce.v1.ProductCatalogService/BulkAddProducts',
                request_serializer=ecommerce_dot_v1_dot_product__pb2.BulkAddProductsRequest.SerializeToString,
                response_deserializer=ecommerce_dot_v1_dot_product__pb2.BulkAddProductsResponse.FromString,
                _registered_method=True)
        self.QuoteProducts = channel.stream_stream(
                '/ecommerce.v1.ProductCatalogService/QuoteProducts',
                request_serializer=ecommerce_dot_v1_dot_product__pb2.QuoteProductsRequest.SerializeToString,
                response_deserializer=ecommerce_dot_v1_dot_product__pb2.QuoteProductsResponse.FromString,
                _registered_method=True)


class ProductCatalogServiceServicer:
    """ProductCatalogService stores products and prices them.
    """

    def AddProduct(self, request, context):
        """AddProduct stores a new product and returns it with its server-assigned
        ID. Sending the same request_id again returns the product the first
        attempt created instead of a duplicate, which makes retries safe.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetProduct(self, request, context):
        """GetProduct returns one product by ID.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SearchProducts(self, request, context):
        """SearchProducts streams every product whose name or description contains
        the query, case-insensitively, ordered by name. An empty query matches
        everything.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BulkAddProducts(self, request_iterator, context):
        """BulkAddProducts stores every streamed product atomically: either all of
        them are added or, if any is invalid, none is.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def QuoteProducts(self, request_iterator, context):
        """QuoteProducts answers each streamed (product, quantity) pair with a price
        as soon as it arrives. A bad item gets an error status in its response;
        the stream carries on.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ProductCatalogServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AddProduct': grpc.unary_unary_rpc_method_handler(
                    servicer.AddProduct,
                    request_deserializer=ecommerce_dot_v1_dot_product__pb2.AddProductRequest.FromString,
                    response_serializer=ecommerce_dot_v1_dot_product__pb2.AddProductResponse.SerializeToString,
            ),
            'GetProduct': grpc.unary_unary_rpc_method_handler(
                    servicer.GetProduct,
                    request_deserializer=ecommerce_dot_v1_dot_product__pb2.GetProductRequest.FromString,
                    response_serializer=ecommerce_dot_v1_dot_product__pb2.GetProductResponse.SerializeToString,
            ),
            'SearchProducts': grpc.unary_stream_rpc_method_handler(
                    servicer.SearchProducts,
                    request_deserializer=ecommerce_dot_v1_dot_product__pb2.SearchProductsRequest.FromString,
                    response_serializer=ecommerce_dot_v1_dot_product__pb2.SearchProductsResponse.SerializeToString,
            ),
            'BulkAddProducts': grpc.stream_unary_rpc_method_handler(
                    servicer.BulkAddProducts,
                    request_deserializer=ecommerce_dot_v1_dot_product__pb2.BulkAddProductsRequest.FromString,
                    response_serializer=ecommerce_dot_v1_dot_product__pb2.BulkAddProductsResponse.SerializeToString,
            ),
            'QuoteProducts': grpc.stream_stream_rpc_method_handler(
                    servicer.QuoteProducts,
                    request_deserializer=ecommerce_dot_v1_dot_product__pb2.QuoteProductsRequest.FromString,
                    response_serializer=ecommerce_dot_v1_dot_product__pb2.QuoteProductsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ecommerce.v1.ProductCatalogService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ecommerce.v1.ProductCatalogService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ProductCatalogService:
    """ProductCatalogService stores products and prices them.
    """

    @staticmethod
    def AddProduct(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ecommerce.v1.ProductCatalogService/AddProduct',
            ecommerce_dot_v1_dot_product__pb2.AddProductRequest.SerializeToString,
            ecommerce_dot_v1_dot_product__pb2.AddProductResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetProduct(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ecommerce.v1.ProductCatalogService/GetProduct',
            ecommerce_dot_v1_dot_product__pb2.GetProductRequest.SerializeToString,
            ecommerce_dot_v1_dot_product__pb2.GetProductResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SearchProducts(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/ecommerce.v1.ProductCatalogService/SearchProducts',
            ecommerce_dot_v1_dot_product__pb2.SearchProductsRequest.SerializeToString,
            ecommerce_dot_v1_dot_product__pb2.SearchProductsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BulkAddProducts(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/ecommerce.v1.ProductCatalogService/BulkAddProducts',
            ecommerce_dot_v1_dot_product__pb2.BulkAddProductsRequest.SerializeToString,
            ecommerce_dot_v1_dot_product__pb2.BulkAddProductsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def QuoteProducts(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/ecommerce.v1.ProductCatalogService/QuoteProducts',
            ecommerce_dot_v1_dot_product__pb2.QuoteProductsRequest.SerializeToString,
            ecommerce_dot_v1_dot_product__pb2.QuoteProductsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
