"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
Product catalog API. It exists to exercise every gRPC communication
pattern (unary, server streaming, client streaming and bidirectional
streaming) on one small, realistic domain.
"""

from collections import abc as _abc
from ecommerce.v1 import product_pb2 as _product_pb2
from grpc import aio as _aio
import abc as _abc_1
import grpc as _grpc
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import Self as _Self
else:
    from typing_extensions import Self as _Self

_T = _typing.TypeVar("_T")

class _MaybeAsyncIterator(_abc.AsyncIterator[_T], _abc.Iterator[_T], metaclass=_abc_1.ABCMeta): ...

class _ServicerContext(_grpc.ServicerContext, _aio.ServicerContext):  # type: ignore[misc, type-arg]
    ...

GRPC_GENERATED_VERSION: str
GRPC_VERSION: str

class ProductCatalogServiceStub:
    """ProductCatalogService stores products and prices them."""

    @_typing.overload
    def __new__(cls, channel: _grpc.Channel) -> _Self: ...
    @_typing.overload
    def __new__(cls, channel: _aio.Channel) -> ProductCatalogServiceAsyncStub: ...
    AddProduct: _grpc.UnaryUnaryMultiCallable[_product_pb2.AddProductRequest, _product_pb2.AddProductResponse]
    """AddProduct stores a new product and returns it with its server-assigned
    ID. Sending the same request_id again returns the product the first
    attempt created instead of a duplicate, which makes retries safe.
    """
    GetProduct: _grpc.UnaryUnaryMultiCallable[_product_pb2.GetProductRequest, _product_pb2.GetProductResponse]
    """GetProduct returns one product by ID."""
    SearchProducts: _grpc.UnaryStreamMultiCallable[_product_pb2.SearchProductsRequest, _product_pb2.SearchProductsResponse]
    """SearchProducts streams every product whose name or description contains
    the query, case-insensitively, ordered by name. An empty query matches
    everything.
    """
    BulkAddProducts: _grpc.StreamUnaryMultiCallable[_product_pb2.BulkAddProductsRequest, _product_pb2.BulkAddProductsResponse]
    """BulkAddProducts stores every streamed product atomically: either all of
    them are added or, if any is invalid, none is.
    """
    QuoteProducts: _grpc.StreamStreamMultiCallable[_product_pb2.QuoteProductsRequest, _product_pb2.QuoteProductsResponse]
    """QuoteProducts answers each streamed (product, quantity) pair with a price
    as soon as it arrives. A bad item gets an error status in its response;
    the stream carries on.
    """

@_typing.type_check_only
class ProductCatalogServiceAsyncStub(ProductCatalogServiceStub):
    """ProductCatalogService stores products and prices them."""

    def __init__(self, channel: _aio.Channel) -> None: ...
    AddProduct: _aio.UnaryUnaryMultiCallable[_product_pb2.AddProductRequest, _product_pb2.AddProductResponse]  # type: ignore[assignment]
    """AddProduct stores a new product and returns it with its server-assigned
    ID. Sending the same request_id again returns the product the first
    attempt created instead of a duplicate, which makes retries safe.
    """
    GetProduct: _aio.UnaryUnaryMultiCallable[_product_pb2.GetProductRequest, _product_pb2.GetProductResponse]  # type: ignore[assignment]
    """GetProduct returns one product by ID."""
    SearchProducts: _aio.UnaryStreamMultiCallable[_product_pb2.SearchProductsRequest, _product_pb2.SearchProductsResponse]  # type: ignore[assignment]
    """SearchProducts streams every product whose name or description contains
    the query, case-insensitively, ordered by name. An empty query matches
    everything.
    """
    BulkAddProducts: _aio.StreamUnaryMultiCallable[_product_pb2.BulkAddProductsRequest, _product_pb2.BulkAddProductsResponse]  # type: ignore[assignment]
    """BulkAddProducts stores every streamed product atomically: either all of
    them are added or, if any is invalid, none is.
    """
    QuoteProducts: _aio.StreamStreamMultiCallable[_product_pb2.QuoteProductsRequest, _product_pb2.QuoteProductsResponse]  # type: ignore[assignment]
    """QuoteProducts answers each streamed (product, quantity) pair with a price
    as soon as it arrives. A bad item gets an error status in its response;
    the stream carries on.
    """

class ProductCatalogServiceServicer(metaclass=_abc_1.ABCMeta):
    """ProductCatalogService stores products and prices them."""

    @_abc_1.abstractmethod
    def AddProduct(
        self,
        request: _product_pb2.AddProductRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_product_pb2.AddProductResponse, _abc.Awaitable[_product_pb2.AddProductResponse]]:
        """AddProduct stores a new product and returns it with its server-assigned
        ID. Sending the same request_id again returns the product the first
        attempt created instead of a duplicate, which makes retries safe.
        """

    @_abc_1.abstractmethod
    def GetProduct(
        self,
        request: _product_pb2.GetProductRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_product_pb2.GetProductResponse, _abc.Awaitable[_product_pb2.GetProductResponse]]:
        """GetProduct returns one product by ID."""

    @_abc_1.abstractmethod
    def SearchProducts(
        self,
        request: _product_pb2.SearchProductsRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_abc.Iterator[_product_pb2.SearchProductsResponse], _abc.AsyncIterator[_product_pb2.SearchProductsResponse]]:
        """SearchProducts streams every product whose name or description contains
        the query, case-insensitively, ordered by name. An empty query matches
        everything.
        """

    @_abc_1.abstractmethod
    def BulkAddProducts(
        self,
        request_iterator: _MaybeAsyncIterator[_product_pb2.BulkAddProductsRequest],
        context: _ServicerContext,
    ) -> _typing.Union[_product_pb2.BulkAddProductsResponse, _abc.Awaitable[_product_pb2.BulkAddProductsResponse]]:
        """BulkAddProducts stores every streamed product atomically: either all of
        them are added or, if any is invalid, none is.
        """

    @_abc_1.abstractmethod
    def QuoteProducts(
        self,
        request_iterator: _MaybeAsyncIterator[_product_pb2.QuoteProductsRequest],
        context: _ServicerContext,
    ) -> _typing.Union[_abc.Iterator[_product_pb2.QuoteProductsResponse], _abc.AsyncIterator[_product_pb2.QuoteProductsResponse]]:
        """QuoteProducts answers each streamed (product, quantity) pair with a price
        as soon as it arrives. A bad item gets an error status in its response;
        the stream carries on.
        """

def add_ProductCatalogServiceServicer_to_server(servicer: ProductCatalogServiceServicer, server: _typing.Union[_grpc.Server, _aio.Server]) -> None: ...
