"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
Product catalog API. It exists to exercise every gRPC communication
pattern (unary, server streaming, client streaming and bidirectional
streaming) on one small, realistic domain.
"""

from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import containers as _containers
from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import TypeAlias as _TypeAlias, Never as _Never
else:
    from typing_extensions import TypeAlias as _TypeAlias, Never as _Never

DESCRIPTOR: _descriptor.FileDescriptor

class _QuoteStatus:
    ValueType = _typing.NewType("ValueType", _builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015

class _QuoteStatusEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_QuoteStatus.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    QUOTE_STATUS_UNSPECIFIED: _QuoteStatus.ValueType  # 0
    """Never sent; the proto3 default."""
    QUOTE_STATUS_OK: _QuoteStatus.ValueType  # 1
    """total_cents holds the price."""
    QUOTE_STATUS_NOT_FOUND: _QuoteStatus.ValueType  # 2
    """No product has that ID."""
    QUOTE_STATUS_INVALID_QUANTITY: _QuoteStatus.ValueType  # 3
    """The quantity is outside 1 to 1,000,000."""

class QuoteStatus(_QuoteStatus, metaclass=_QuoteStatusEnumTypeWrapper):
    """QuoteStatus is the outcome of one quote."""

QUOTE_STATUS_UNSPECIFIED: QuoteStatus.ValueType  # 0
"""Never sent; the proto3 default."""
QUOTE_STATUS_OK: QuoteStatus.ValueType  # 1
"""total_cents holds the price."""
QUOTE_STATUS_NOT_FOUND: QuoteStatus.ValueType  # 2
"""No product has that ID."""
QUOTE_STATUS_INVALID_QUANTITY: QuoteStatus.ValueType  # 3
"""The quantity is outside 1 to 1,000,000."""
Global___QuoteStatus: _TypeAlias = QuoteStatus  # noqa: Y015

@_typing.final
class Product(_message.Message):
    """Product is a catalog entry."""

    DESCRIPTOR: _descriptor.Descriptor

    ID_FIELD_NUMBER: _builtins.int
    NAME_FIELD_NUMBER: _builtins.int
    DESCRIPTION_FIELD_NUMBER: _builtins.int
    PRICE_CENTS_FIELD_NUMBER: _builtins.int
    id: _builtins.str
    """Server-assigned identifier (a UUID). Clients never choose it."""
    name: _builtins.str
    """Display name, 1 to 200 characters, unique case-insensitively."""
    description: _builtins.str
    """Free text, up to 2000 characters."""
    price_cents: _builtins.int
    """Price in the smallest currency unit, so no floating-point rounding."""
    def __init__(
        self,
        *,
        id: _builtins.str = ...,
        name: _builtins.str = ...,
        description: _builtins.str = ...,
        price_cents: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["description", b"description", "id", b"id", "name", b"name", "price_cents", b"price_cents"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___Product: _TypeAlias = Product  # noqa: Y015

@_typing.final
class NewProduct(_message.Message):
    """NewProduct is what a client supplies to create a product."""

    DESCRIPTOR: _descriptor.Descriptor

    NAME_FIELD_NUMBER: _builtins.int
    DESCRIPTION_FIELD_NUMBER: _builtins.int
    PRICE_CENTS_FIELD_NUMBER: _builtins.int
    name: _builtins.str
    """See Product.name."""
    description: _builtins.str
    """See Product.description."""
    price_cents: _builtins.int
    """See Product.price_cents. Zero or more."""
    def __init__(
        self,
        *,
        name: _builtins.str = ...,
        description: _builtins.str = ...,
        price_cents: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["description", b"description", "name", b"name", "price_cents", b"price_cents"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___NewProduct: _TypeAlias = NewProduct  # noqa: Y015

@_typing.final
class AddProductRequest(_message.Message):
    """AddProductRequest creates one product."""

    DESCRIPTOR: _descriptor.Descriptor

    PRODUCT_FIELD_NUMBER: _builtins.int
    REQUEST_ID_FIELD_NUMBER: _builtins.int
    request_id: _builtins.str
    """Optional idempotency key (AIP-155). A retry with the same key returns
    the product the first attempt created. Reusing a key for a different
    product is rejected with FAILED_PRECONDITION.
    """
    @_builtins.property
    def product(self) -> Global___NewProduct:
        """The product to create."""

    def __init__(
        self,
        *,
        product: Global___NewProduct | None = ...,
        request_id: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["product", b"product"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["product", b"product", "request_id", b"request_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___AddProductRequest: _TypeAlias = AddProductRequest  # noqa: Y015

@_typing.final
class AddProductResponse(_message.Message):
    """AddProductResponse carries the stored product."""

    DESCRIPTOR: _descriptor.Descriptor

    PRODUCT_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def product(self) -> Global___Product:
        """The product as stored, with its ID."""

    def __init__(
        self,
        *,
        product: Global___Product | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["product", b"product"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["product", b"product"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___AddProductResponse: _TypeAlias = AddProductResponse  # noqa: Y015

@_typing.final
class GetProductRequest(_message.Message):
    """GetProductRequest names one product."""

    DESCRIPTOR: _descriptor.Descriptor

    ID_FIELD_NUMBER: _builtins.int
    id: _builtins.str
    """The product's ID."""
    def __init__(
        self,
        *,
        id: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["id", b"id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___GetProductRequest: _TypeAlias = GetProductRequest  # noqa: Y015

@_typing.final
class GetProductResponse(_message.Message):
    """GetProductResponse carries the requested product."""

    DESCRIPTOR: _descriptor.Descriptor

    PRODUCT_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def product(self) -> Global___Product:
        """The product."""

    def __init__(
        self,
        *,
        product: Global___Product | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["product", b"product"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["product", b"product"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___GetProductResponse: _TypeAlias = GetProductResponse  # noqa: Y015

@_typing.final
class SearchProductsRequest(_message.Message):
    """SearchProductsRequest filters the catalog."""

    DESCRIPTOR: _descriptor.Descriptor

    QUERY_FIELD_NUMBER: _builtins.int
    query: _builtins.str
    """Case-insensitive substring of the name or description."""
    def __init__(
        self,
        *,
        query: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["query", b"query"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___SearchProductsRequest: _TypeAlias = SearchProductsRequest  # noqa: Y015

@_typing.final
class SearchProductsResponse(_message.Message):
    """SearchProductsResponse is one match."""

    DESCRIPTOR: _descriptor.Descriptor

    PRODUCT_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def product(self) -> Global___Product:
        """A matching product."""

    def __init__(
        self,
        *,
        product: Global___Product | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["product", b"product"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["product", b"product"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___SearchProductsResponse: _TypeAlias = SearchProductsResponse  # noqa: Y015

@_typing.final
class BulkAddProductsRequest(_message.Message):
    """BulkAddProductsRequest is one product of a bulk add."""

    DESCRIPTOR: _descriptor.Descriptor

    PRODUCT_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def product(self) -> Global___NewProduct:
        """The product to create."""

    def __init__(
        self,
        *,
        product: Global___NewProduct | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["product", b"product"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["product", b"product"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___BulkAddProductsRequest: _TypeAlias = BulkAddProductsRequest  # noqa: Y015

@_typing.final
class BulkAddProductsResponse(_message.Message):
    """BulkAddProductsResponse lists every product the bulk add stored."""

    DESCRIPTOR: _descriptor.Descriptor

    PRODUCTS_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def products(self) -> _containers.RepeatedCompositeFieldContainer[Global___Product]:
        """The stored products, in the order they were sent."""

    def __init__(
        self,
        *,
        products: _abc.Iterable[Global___Product] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["products", b"products"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___BulkAddProductsResponse: _TypeAlias = BulkAddProductsResponse  # noqa: Y015

@_typing.final
class QuoteProductsRequest(_message.Message):
    """QuoteProductsRequest asks for the price of a quantity of one product."""

    DESCRIPTOR: _descriptor.Descriptor

    PRODUCT_ID_FIELD_NUMBER: _builtins.int
    QUANTITY_FIELD_NUMBER: _builtins.int
    product_id: _builtins.str
    """The product to price."""
    quantity: _builtins.int
    """How many, from 1 to 1,000,000."""
    def __init__(
        self,
        *,
        product_id: _builtins.str = ...,
        quantity: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["product_id", b"product_id", "quantity", b"quantity"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___QuoteProductsRequest: _TypeAlias = QuoteProductsRequest  # noqa: Y015

@_typing.final
class QuoteProductsResponse(_message.Message):
    """QuoteProductsResponse answers one QuoteProductsRequest."""

    DESCRIPTOR: _descriptor.Descriptor

    PRODUCT_ID_FIELD_NUMBER: _builtins.int
    QUANTITY_FIELD_NUMBER: _builtins.int
    STATUS_FIELD_NUMBER: _builtins.int
    TOTAL_CENTS_FIELD_NUMBER: _builtins.int
    product_id: _builtins.str
    """Echoed from the request."""
    quantity: _builtins.int
    """Echoed from the request."""
    status: Global___QuoteStatus.ValueType
    """Whether the quote succeeded."""
    total_cents: _builtins.int
    """quantity * price_cents. Set only when status is QUOTE_STATUS_OK."""
    def __init__(
        self,
        *,
        product_id: _builtins.str = ...,
        quantity: _builtins.int = ...,
        status: Global___QuoteStatus.ValueType = ...,
        total_cents: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["product_id", b"product_id", "quantity", b"quantity", "status", b"status", "total_cents", b"total_cents"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___QuoteProductsResponse: _TypeAlias = QuoteProductsResponse  # noqa: Y015
