// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protos/productInfo.proto

package ecommerce

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// message to encompass metadata for a product
type Product struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description          string   `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Product) Reset()         { *m = Product{} }
func (m *Product) String() string { return proto.CompactTextString(m) }
func (*Product) ProtoMessage()    {}
func (*Product) Descriptor() ([]byte, []int) {
	return fileDescriptor_6de13d1e0398433e, []int{0}
}

func (m *Product) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Product.Unmarshal(m, b)
}
func (m *Product) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Product.Marshal(b, m, deterministic)
}
func (m *Product) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Product.Merge(m, src)
}
func (m *Product) XXX_Size() int {
	return xxx_messageInfo_Product.Size(m)
}
func (m *Product) XXX_DiscardUnknown() {
	xxx_messageInfo_Product.DiscardUnknown(m)
}

var xxx_messageInfo_Product proto.InternalMessageInfo

func (m *Product) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Product) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Product) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

// custom user defined message for messageIds
type ProductID struct {
	Value                string   `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProductID) Reset()         { *m = ProductID{} }
func (m *ProductID) String() string { return proto.CompactTextString(m) }
func (*ProductID) ProtoMessage()    {}
func (*ProductID) Descriptor() ([]byte, []int) {
	return fileDescriptor_6de13d1e0398433e, []int{1}
}

func (m *ProductID) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProductID.Unmarshal(m, b)
}
func (m *ProductID) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProductID.Marshal(b, m, deterministic)
}
func (m *ProductID) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProductID.Merge(m, src)
}
func (m *ProductID) XXX_Size() int {
	return xxx_messageInfo_ProductID.Size(m)
}
func (m *ProductID) XXX_DiscardUnknown() {
	xxx_messageInfo_ProductID.DiscardUnknown(m)
}

var xxx_messageInfo_ProductID proto.InternalMessageInfo

func (m *ProductID) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func init() {
	proto.RegisterType((*Product)(nil), "ecommerce.Product")
	proto.RegisterType((*ProductID)(nil), "ecommerce.ProductID")
}

func init() {
	proto.RegisterFile("protos/productInfo.proto", fileDescriptor_6de13d1e0398433e)
}

var fileDescriptor_6de13d1e0398433e = []byte{
	// 202 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x28, 0x28, 0xca, 0x2f,
	0xc9, 0x2f, 0xd6, 0x2f, 0x28, 0xca, 0x4f, 0x29, 0x4d, 0x2e, 0xf1, 0xcc, 0x4b, 0xcb, 0xd7, 0x03,
	0x0b, 0x09, 0x71, 0xa6, 0x26, 0xe7, 0xe7, 0xe6, 0xa6, 0x16, 0x25, 0xa7, 0x2a, 0xf9, 0x73, 0xb1,
	0x07, 0x40, 0xe4, 0x85, 0xf8, 0xb8, 0x98, 0x32, 0x53, 0x24, 0x18, 0x15, 0x18, 0x35, 0x38, 0x83,
	0x98, 0x32, 0x53, 0x84, 0x84, 0xb8, 0x58, 0xf2, 0x12, 0x73, 0x53, 0x25, 0x98, 0xc0, 0x22, 0x60,
	0xb6, 0x90, 0x02, 0x17, 0x77, 0x4a, 0x6a, 0x71, 0x72, 0x51, 0x66, 0x41, 0x49, 0x66, 0x7e, 0x9e,
	0x04, 0x33, 0x58, 0x0a, 0x59, 0x48, 0x49, 0x91, 0x8b, 0x13, 0x6a, 0xa0, 0xa7, 0x8b, 0x90, 0x08,
	0x17, 0x6b, 0x59, 0x62, 0x4e, 0x69, 0x2a, 0xd4, 0x54, 0x08, 0xc7, 0xa8, 0x96, 0x8b, 0x3b, 0x00,
	0xe1, 0x26, 0x21, 0x33, 0x2e, 0xae, 0xc4, 0x94, 0x14, 0x98, 0x2b, 0x84, 0xf4, 0xe0, 0x8e, 0xd3,
	0x83, 0x8a, 0x49, 0x89, 0x60, 0x8a, 0x79, 0xba, 0x80, 0xf4, 0xa5, 0xa7, 0x96, 0xc0, 0xf4, 0x61,
	0x55, 0x23, 0x85, 0xc5, 0x34, 0x27, 0xd1, 0x28, 0x61, 0x68, 0x90, 0x64, 0xe6, 0xa5, 0xe5, 0xeb,
	0x17, 0xa7, 0x16, 0x95, 0x65, 0x26, 0xa7, 0x26, 0xb1, 0x81, 0xc3, 0xc6, 0x18, 0x10, 0x00, 0x00,
	0xff, 0xff, 0x33, 0x7c, 0x14, 0x2d, 0x37, 0x01, 0x00, 0x00,
}
